=== fermo-metabolomics/fermo_core/fermo_core/config/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$schema_version": "1.1.0",
  "type": "object",
  "properties": {
    "PeaktableParameters": {
      "type": "object",
      "properties": {
        "filepath": {
          "type": "string"
        },
        "format": {
          "type": "string",
          "enum": [
            "mzmine3",
            "mzmine4"
          ]
        },
        "polarity": {
          "type": "string",
          "enum": [
            "positive",
            "negative"
          ]
        }
      }
    },
    "MsmsParameters": {
      "type": "object",
      "properties": {
        "filepath": {
          "type": "string"
        },
        "format": {
          "type": "string",
          "enum": [
            "mgf"
          ]
        },
        "rel_int_from": {
          "$ref": "#/$defs/r_perc"
        }
      }
    },
    "PhenotypeParameters": {
      "type": "object",
      "properties": {
        "filepath": {
          "type": "string"
        },
        "format": {
          "type": "string",
          "enum": [
            "qualitative",
            "quantitative-percentage",
            "quantitative-concentration"
          ]
        }
      }
    },
    "GroupMetadataParameters": {
      "type": "object",
      "properties": {
        "filepath": {
          "type": "string"
        },
        "format": {
          "type": "string",
          "enum": [
            "fermo"
          ]
        }
      }
    },
    "SpecLibParameters": {
      "type": "object",
      "properties": {
        "dirpath": {
          "type": "string"
        },
        "format": {
          "type": "string",
          "enum": [
            "mgf"
          ]
        }
      }
    },
    "MS2QueryResultsParameters": {
      "type": "object",
      "properties": {
        "filepath": {
          "type": "string"
        },
        "score_cutoff": {
          "$ref": "#/$defs/r_perc"
        }
      }
    },
    "AsResultsParameters": {
      "type": "object",
      "properties": {
        "directory_path": {
          "type": "string"
        },
        "similarity_cutoff": {
          "$ref": "#/$defs/r_perc"
        }
      }
    },
    "AdductAnnotationParameters": {
      "type": "object",
      "properties": {
        "activate_module": { "type": "boolean" },
        "mass_dev_ppm": {
          "$ref": "#/$defs/pos_float"
        }
      }
    },
    "NeutralLossParameters": {
      "type": "object",
      "properties": {
        "activate_module": { "type": "boolean" },
        "mass_dev_ppm": {
          "$ref": "#/$defs/pos_float"
        }
      }
    },
    "FragmentAnnParameters": {
      "type": "object",
      "properties": {
        "activate_module": { "type": "boolean" },
        "mass_dev_ppm": {
          "$ref": "#/$defs/pos_float"
        }
      }
    },
    "SpecSimNetworkCosineParameters": {
      "type": "object",
      "properties": {
        "activate_module": { "type": "boolean" },
        "msms_min_frag_nr": {
          "$ref": "#/$defs/pos_int"
        },
        "fragment_tol": {
          "$ref": "#/$defs/pos_float"
        },
        "score_cutoff": {
          "$ref": "#/$defs/r_perc"
        },
        "max_nr_links": {
          "$ref": "#/$defs/pos_int"
        }
      }
    },
    "SpecSimNetworkDeepscoreParameters": {
      "type": "object",
      "properties": {
        "activate_module": { "type": "boolean" },
        "msms_min_frag_nr": {
          "$ref": "#/$defs/pos_int"
        },
        "fragment_tol": {
          "$ref": "#/$defs/pos_float"
        },
        "score_cutoff": {
          "$ref": "#/$defs/r_perc"
        },
        "max_nr_links": {
          "$ref": "#/$defs/pos_int"
        }
      }
    },
    "FeatureFilteringParameters": {
      "type": "object",
      "properties": {
        "activate_module": { "type": "boolean" },
        "filter_rel_int_range_min": {
          "$ref": "#/$defs/r_perc"
        },
        "filter_rel_int_range_max": {
          "$ref": "#/$defs/r_perc"
        },
        "filter_rel_area_range_min": {
          "$ref": "#/$defs/r_perc"
        },
        "filter_rel_area_range_max": {
          "$ref": "#/$defs/r_perc"
        }
      }
    },
    "BlankAssignmentParameters": {
      "type": "object",
      "properties": {
        "activate_module": { "type": "boolean" },
        "factor": {
          "$ref": "#/$defs/pos_int"
        },
        "algorithm": {
          "type": "string",
          "enum": [
            "mean",
            "median",
            "maximum"
          ]
        },
        "value": {
          "type": "string",
          "enum": [
            "height",
            "area"
          ]
        }
      }
    },
    "GroupFactAssignmentParameters": {
      "type": "object",
      "properties": {
        "activate_module": { "type": "boolean" },
        "algorithm": {
          "type": "string",
          "enum": [
            "mean",
            "median",
            "maximum"
          ]
        },
        "value": {
          "type": "string",
          "enum": [
            "height",
            "area"
          ]
        }
      }
    },
    "PhenoQualAssgnParameters": {
      "type": "object",
      "properties": {
        "activate_module": { "type": "boolean" },
        "factor": { "$ref": "#/$defs/pos_int" },
        "algorithm": {
          "type": "string",
          "enum": [
            "minmax",
            "mean",
            "median"
          ]
        },
        "value": {
          "type": "string",
          "enum": [
            "height",
            "area"
          ]
        },
        "p_val_cutoff": {
          "$ref": "#/$defs/r_perc"
        }
      }
    },
    "PhenoQuantPercentAssgnParameters": {
      "$ref": "#/$defs/quant_phen"
    },
    "PhenoQuantConcAssgnParameters": {
      "$ref": "#/$defs/quant_phen"
    },
    "SpectralLibMatchingCosineParameters": {
      "$ref": "#/$defs/cosine_match"
    },
    "SpectralLibMatchingDeepscoreParameters": {
      "$ref": "#/$defs/deepscore_match"
    },
    "AsKcbCosineMatchingParameters": {
      "$ref": "#/$defs/cosine_match"
    },
    "AsKcbDeepscoreMatchingParameters": {
      "$ref": "#/$defs/deepscore_match"
    }
  },
  "$defs": {
    "quant_phen": {
      "type": "object",
      "properties": {
        "activate_module": { "type": "boolean" },
        "sample_avg": {
          "type": "string",
          "enum": ["mean", "median"]
        },
        "value": {
          "type": "string",
          "enum": ["area"]
        },
        "algorithm": {
          "type": "string",
          "enum": ["pearson", "spearman", "spearman_permutation"]
        },
        "fdr_corr": {
          "type": "string",
          "enum": [
            "bonferroni", "sidak", "holm-sidak", "holm",
            "simes-hochberg", "hommel", "fdr_bh", "fdr_by",
            "fdr_tsbh", "fdr_tsbky"
          ]
        },
        "p_val_cutoff": {
          "$ref": "#/$defs/r_perc"
        },
        "coeff_cutoff": {
          "$ref": "#/$defs/r_perc"
        }
      }
    },
    "cosine_match": {
      "type": "object",
      "properties": {
        "activate_module": { "type": "boolean" },
        "fragment_tol": { "$ref": "#/$defs/pos_float" },
        "min_nr_matched_peaks": { "$ref": "#/$defs/pos_int" },
        "score_cutoff": { "$ref": "#/$defs/r_perc" },
        "max_precursor_mass_diff": { "$ref": "#/$defs/pos_int" }
      }
    },
    "deepscore_match": {
      "type": "object",
      "properties": {
        "activate_module": { "type": "boolean" },
        "score_cutoff": { "$ref": "#/$defs/r_perc" },
        "max_precursor_mass_diff": { "$ref": "#/$defs/pos_int" }
      }
    },
    "r_perc": {
      "type": "number",
      "minimum": 0.0,
      "maximum": 1.0
    },
    "pos_int": {
      "type": "integer",
      "minimum": 0
    },
    "pos_float": {
      "type": "number",
      "minimum": 0
    }
  }
}

=== fermo-metabolomics/fermo_core/tests/test_data/test.parameters.json
{
    "PeaktableParameters": {
        "filepath": "tests/test_data/test.peak_table_quant_full.csv",
        "format": "mzmine3",
        "polarity": "positive"
    },
    "MsmsParameters": {
        "filepath": "tests/test_data/test.msms.mgf",
        "format": "mgf",
        "rel_int_from": 0.01
    },
    "PhenotypeParameters": {
        "filepath": "tests/test_data/test.bioactivity.qualitative.csv",
        "format": "qualitative"
    },
    "GroupMetadataParameters": {
        "filepath": "tests/test_data/test.group_metadata.csv",
        "format": "fermo"
    },
    "SpecLibParameters": {
        "dirpath": "tests/test_data/spec_lib/",
        "format": "mgf"
    },
    "MS2QueryResultsParameters": {
        "filepath": "tests/test_data/test.ms2query_results.csv",
        "score_cutoff": 0.7
    },
    "AsResultsParameters": {
        "directory_path": "tests/test_data/JABTEZ000000000.1/",
        "similarity_cutoff": 0.7
    },
    "AdductAnnotationParameters": {
        "activate_module": true,
        "mass_dev_ppm": 10.0
    },
    "NeutralLossParameters": {
        "activate_module": true,
        "mass_dev_ppm": 10.0
    },
    "FragmentAnnParameters": {
        "activate_module": true,
        "mass_dev_ppm": 10.0
    },
    "SpecSimNetworkCosineParameters": {
        "activate_module": true,
        "msms_min_frag_nr": 5,
        "fragment_tol": 0.1,
        "score_cutoff": 0.7,
        "max_nr_links": 10
    },
    "SpecSimNetworkDeepscoreParameters": {
        "activate_module": true,
        "score_cutoff": 0.8,
        "max_nr_links": 10,
        "msms_min_frag_nr": 5
    },
    "FeatureFilteringParameters": {
        "activate_module": true,
        "filter_rel_int_range_min": 0.1,
        "filter_rel_int_range_max": 1.0,
        "filter_rel_area_range_min": 0.1,
        "filter_rel_area_range_max": 1.0
    },
    "BlankAssignmentParameters": {
        "activate_module": true,
        "factor": 10,
        "algorithm": "mean",
        "value": "area"
    },
    "GroupFactAssignmentParameters": {
        "activate_module": true,
        "algorithm": "mean",
        "value": "area"
    },
    "PhenoQualAssgnParameters": {
        "activate_module": true,
        "factor": 5,
        "algorithm": "minmax",
        "value": "area",
        "p_val_cutoff": 0.05
    },
    "PhenoQuantPercentAssgnParameters": {
        "activate_module": false,
        "sample_avg": "mean",
        "value": "area",
        "fdr_corr": "bonferroni",
        "algorithm": "pearson",
        "p_val_cutoff": 0.05,
        "coeff_cutoff": 0.7
    },
    "PhenoQuantConcAssgnParameters": {
        "activate_module": false,
        "sample_avg": "mean",
        "value": "area",
        "fdr_corr": "bonferroni",
        "algorithm": "pearson",
        "p_val_cutoff": 0.05,
        "coeff_cutoff": 0.7
    },
    "SpectralLibMatchingCosineParameters": {
        "activate_module": true,
        "fragment_tol": 0.1,
        "min_nr_matched_peaks": 5,
        "score_cutoff": 0.7,
        "max_precursor_mass_diff": 600
    },
    "SpectralLibMatchingDeepscoreParameters": {
        "activate_module": true,
        "score_cutoff": 0.8,
        "max_precursor_mass_diff": 600
    },
    "AsKcbCosineMatchingParameters": {
        "activate_module": true,
        "fragment_tol": 0.1,
        "min_nr_matched_peaks": 5,
        "score_cutoff": 0.5,
        "max_precursor_mass_diff": 600
    },
    "AsKcbDeepscoreMatchingParameters": {
        "activate_module": true,
        "score_cutoff": 0.7,
        "max_precursor_mass_diff": 600
    }
}
